Models/ClsAleatorio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Laboratorio4_mvc_Maldonado.Models
{
    public class ClsAleatorio
    {
        public int a { get; set; }
        public int b { get; set; }
        public int c { get; set; }
        public string resultado { get; set; }
    }
}

Models/ClsEncuesta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Laboratorio4_mvc_Maldonado.Models
{
    public class ClsEncuesta
    {
        public string pregunta1 { get; set; }
        public string pregunta2 { get; set; }
        public string pregunta3 { get; set; }

        public int votos1 { get; set; }
        public int votos2 { get; set; }
        public int votos3 { get; set; }
        
        public double porcentaje1 { get; set; }
        public double porcentaje2 { get; set; }
        public double porcentaje3 { get; set; }

        public int totalvotos { get; set; }
        public double totalporcentaje { get; set; }


    }
}

Models/ClsVenta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Laboratorio4_mvc_Maldonado.Models
{
    public class ClsVenta
    {
        public bool Cursophp { get; set; }
        public bool CursoWeb { get; set; }
        public bool CursoMovil { get; set; }
        public bool Cursopython { get; set; }

        public double subtotal { get; set; }
        public double precio { get; set; }
        public double igv { get; set; }
        public double total { get; set; }

    }
}

Controllers/AleatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laboratorio4_mvc_Maldonado.Models;

namespace Laboratorio4_mvc_Maldonado.Controllers
{
    public class AleatorioController : Controller
    {
        // GET: Aleatorio
        public ActionResult Index()
        {
            return View();
        }

        
        public ActionResult Generar(ClsAleatorio objAleatorio)
        {
            Random rand = new Random();
            objAleatorio.a = rand.Next(3);
            objAleatorio.b = rand.Next(3);
            objAleatorio.c = rand.Next(3);

            if(objAleatorio.a == objAleatorio.b)
            {
                if (objAleatorio.b == objAleatorio.c)
                {
                    if (objAleatorio.a == objAleatorio.c)
                    {
                        objAleatorio.resultado = "Los 3 numeros son iguales, ganaste una entrada para Rosalia....";
                    }

                }
                else
                {
                    objAleatorio.resultado = "Perdiste... Sigue intentandolo ";
                }

            }
            else
            {
                objAleatorio.resultado = "Para la proxima... ";
            }


            return View(objAleatorio);
        }


    }
}

Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio4_mvc_Maldonado.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/EncuestaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using Laboratorio4_mvc_Maldonado.Models;

namespace Laboratorio4_mvc_Maldonado.Controllers
{
    public class EncuestaController : Controller
    {
        // GET: Encuesta
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Encuestar(ClsEncuesta objEncuensta)
        {
            ViewBag.Pregunta1 = "PHP";
            ViewBag.Pregunta2 = "Python";
            ViewData["Pregunta3"] = "Java";

            objEncuensta.totalvotos = 0;
            objEncuensta.totalporcentaje = 0.0d;
            if (Request["curso"] == "Curso 1")
            {
                int contador = 0;
                if (Session["cv1"] == null)
                {
                    Session["cv1"] = 1;
                }
                else
                {
                    contador = Convert.ToInt32(Session["cv1"]);
                    contador++;
                    Session["cv1"] = contador;
                    objEncuensta.totalvotos += Convert.ToInt32(Session["cv1"]);

                }
            }
            if (Request["curso"] == "Curso 2")
            {
                int contador = 0;
                if (Session["cv2"] == null)
                {
                    Session["cv2"] = 2;
                }
                else
                {
                    contador = Convert.ToInt32(Session["cv2"]);
                    contador++;
                    Session["cv2"] = contador;
                    objEncuensta.totalvotos += Convert.ToInt32(Session["cv2"]);

                }
            }
            if (Request["curso"] == "Curso 3")
            {
                int contador = 0;
                if (Session["cv3"] == null)
                {
                    Session["cv3"] = 3;
                }
                else
                {
                    contador = Convert.ToInt32(Session["cv3"]);
                    contador++;
                    Session["cv3"] = contador;
                    objEncuensta.totalvotos += Convert.ToInt32(Session["cv3"]);

                }
            }
            Session["Totalvotos"] = (Convert.ToInt32(Session["cv1"]) + Convert.ToInt32(Session["cv2"])+ Convert.ToInt32(Session["cv3"]));
            
            Session["vp1"] = (Convert.ToDouble(Session["porC1"]).ToString("0.00"));
            Session["porC1"] = ((Convert.ToDouble(Session["porC1"]) * 100.0d) / Convert.ToDouble(Session["Totalvotos"])).ToString("0.00");

            Session["vp2"] = (Convert.ToDouble(Session["porC2"]).ToString("0.00"));
            Session["porC2"] = ((Convert.ToDouble(Session["porC2"]) * 100.0d) / Convert.ToDouble(Session["Totalvotos"])).ToString("0.00");

            Session["vp3"] = (Convert.ToDouble(Session["porC3"]).ToString("0.00"));
            Session["porC3"] = ((Convert.ToDouble(Session["porC3"]) * 100.0d) / Convert.ToDouble(Session["Totalvotos"])).ToString("0.00");
            return View(objEncuensta);
        }
    }
}

Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laboratorio4_mvc_Maldonado.Models;

namespace Laboratorio4_mvc_Maldonado.Controllers
{
    public class VentaController : Controller
    {
        public static double precioC1 = 500;
        public static double precioC2 = 350;
        public static double precioC3 = 1500;
        public static double precioC4 = 850.99;


        // GET: Venta
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult CalcularVenta(ClsVenta objVenta)
        {
            if (objVenta.Cursophp == true)
            {
                objVenta.subtotal = objVenta.subtotal + precioC1;
            }
            if (objVenta.CursoWeb == true)
            {
                objVenta.subtotal = objVenta.subtotal + precioC2;
            }
            if (objVenta.CursoMovil == true)
            {
                objVenta.subtotal = objVenta.subtotal + precioC3;
            }
            if (objVenta.Cursopython == true)
            {
                objVenta.subtotal = objVenta.subtotal + precioC4;
            }
            objVenta.igv = objVenta.subtotal * 0.18;
            objVenta.total = objVenta.subtotal + objVenta.igv;




            return View(objVenta);
        }

    }
}

Views/Aleatorio/Generar.cshtml
@model Laboratorio4_mvc_Maldonado.Models.ClsAleatorio
@{
    ViewBag.Title = "Generar";
}

<h2>Generar</h2>
<h1>Ganador de Entrada</h1>
<br />

@using (Html.BeginForm("Generar", "Aleatorio", FormMethod.Post))
            {
                <p>
                    @Html.LabelFor(model => model.a, "Ruleta")


                </p><button class="btn btn-info">Jugar</button>
                if (Session["i"] == null)
                {
                    Session["i"] = 1;
                    <h2>? - ? - ?</h2>

                }
                else
                {
                int contador = Convert.ToInt32(Session["i"]);
                contador++;
                Session["i"] = contador;
                <h2>@Model.a - @Model.b - @Model.c  </h2>

                }
}
<br />
@Model.resultado

Views/Default/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<b>Hola Mundo Cruel</b>

Views/Shared/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Laboratorio de 4 MVC</title>
    <link href="~/Source/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Source/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Source/js/jquery-3.6.1.min.js"></script>
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Laboratorio 4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                     
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Ejercicio
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="~/Venta/CalcularVenta">Ejercicio 1</a></li>
                                <li><a class="dropdown-item" href="~/Aleatorio/Generar">Ejercicio 2</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Ejercicio 3</a></li>
                            </ul>
                        </li>
                    
                    </ul>
                   
                </div>
            </div>
        </nav>
    </div>
    <div class="container">
        <h1>
            Laboratorio 4 MVC
        </h1>
        @RenderBody()
    </div>
    <script src="~/Source/js/bootstrap.min.js"></script>
    <script src="~/Source/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/Venta/CalcularVenta.cshtml
@model Laboratorio4_mvc_Maldonado.Models.ClsVenta
@{
    ViewBag.Title = "CalcularVenta";
}

<h2>CalcularVenta</h2>
<div>

    @using (Html.BeginForm("CalcularVenta", "Venta", FormMethod.Post))
            {
                <div>
                    <p>
                        @Html.Label("Curso 1")<br />

                        @Html.CheckBoxFor(model => model.Cursophp, "--") 
                        PHP con Laravel

                    </p>
                    <p>
                        @Html.Label("Curso 2")<br />
                    
                        @Html.CheckBoxFor(model => model.CursoWeb, "--") 
                        Curso de maquetacion y diseño WEB

                    </p>
                    <p>
                        @Html.Label("Curso 3")<br />

                        @Html.CheckBoxFor(model => model.CursoMovil, "--") 
                        ANDROID

                    </p>
                    <p>
                        @Html.Label("Curso 4")<br />

                        @Html.CheckBoxFor(model => model.Cursopython, "--") 
                        Analitica de Datos con Python
                    </p>
                    <p>
                        <label>SubTotal: S/. @Model.subtotal</label><br />
                        <label>IGV S/. @Model.igv</label><br />
                        <label>Total: S/. @Model.total</label><br />

                    </p>
                    <br />
                    <button class="btn btn-primary">Calcular</button>
                    <br />
                </div>
            }


</div>